const api = {
    install: '/api/install',
    script: '/api/script',
    device: '/api/device',
    account: '/api/account',
    material: '/api/material',
    material_count: '/api/material/count',
    publish_job: '/api/publish_job',
    train_job: '/api/train_job',
    shell: '/api/shell',
    init: '/api/device/init',
    group: '/api/group',
    music: '/api/music',
    train_job: '/api/train_job',
    watcher: '/api/dialog_watcher',
    license: '/api/license',
    settings: '/api/settings',
    task_status: '/api/device/task_status',
}
export default api
