const api = {
    install: '/api/install',
    script: '/api/script',
    device: '/api/device',
    account: '/api/account',
    material: '/api/material',
    material_count: '/api/material/count',
    publish_job: '/api/publish_job',
    train_job: '/api/train_job',
    shell: '/api/shell',
    init: '/api/device/init',
    group: '/api/group',
    music: '/api/music',
    train_job: '/api/train_job',
    watcher: '/api/dialog_watcher',
    settings: '/api/settings',
    task_status: '/api/device/task_status',
    get_license: '/api/get_license',
    add_license: '/api/add_license',
    avatar: '/api/avatar',
    count_train_job_by_status: '/api/train_job/count_by_status',
    count_publish_job_by_status: '/api/publish_job/count_by_status',
    count_online_device: '/api/device/count_online',
    count_all_account: '/api/account/count_all',
    count_account_by_group_id: '/api/account/count_by_group_id',
    retry_all_failed_train_job: '/api/train_job/retry_all',
    retry_all_failed_publish_job: '/api/publish_job/retry_all',

}
export default api
